// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhbucjsjbjuaefhyxmxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoYnVjanNqYmp1YWVmaHl4bXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjc2NTIsImV4cCI6MjA2NTkwMzY1Mn0.-dWbEwP3VHSxfYs-eV86Cm6g8xRLOXLy1RFZyp7IDqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);